markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/tariqhamid/confusedprogrammer.com
help_url: https://github.com/tariqhamid/confusedprogrammer.com/confusedprogrammer-help

timezone: UK/London

collections:
  docs:
    output: true

name: Confused Programmer • Complex, muddled, obstructive
description: Convoluted approaches
url: http://confusedprogrammer.com


gems:
  - jekyll-feed
  - jekyll-redirect-from

  
